# Generated by Django 2.0.3 on 2018-04-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
