# Generated by Django 2.0.3 on 2018-04-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentreply_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
