# Generated by Django 2.0.3 on 2018-04-07 04:12

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180407_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=blog.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='document',
        ),
        migrations.AlterField(
            model_name='blog',
            name='topbanner',
            field=models.FileField(blank=True, null=True, upload_to='documents/banner/'),
        ),
        migrations.AddField(
            model_name='document',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
