# Generated by Django 2.0.3 on 2018-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180407_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topbanner',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/documents/03.jpg', null=True, upload_to='documents/banner/'),
        ),
    ]
