# Generated by Django 2.0.3 on 2018-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180407_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topbanner',
            field=models.FileField(blank=True, default='documents/03.jpg', null=True, upload_to='documents/banner/'),
        ),
    ]
