# Generated by Django 2.0.3 on 2018-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180408_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='displayname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
