# Generated by Django 2.0.3 on 2018-04-08 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userimage_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='author',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
