# Generated by Django 2.0.3 on 2018-04-08 18:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180408_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='myimage',
            field=models.ImageField(blank=True, default='user_image_noimg/jobs.jpg', null=True, upload_to=blog.models.get_user_image_filename),
        ),
    ]
